pipeline {
    agent any
    parameters {
       string defaultValue: 'NOOR', name: 'NAME'
}  
    environment{
        NAME = "MUHAMMED"
    }


    tools {
        maven 'mymaven'
    }

    options {
        skipStagesAfterUnstable()
    }

    stages {

        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
                echo "hello $NAME"
            
            }
        }

        stage('Test') {
            steps {
                sh 'mvn test'

            }

            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }

        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}