pipeline {
    agent any
    parameters {
       string defaultValue: 'NOOR', name: 'NAME'
}  
    environment{
        NAME = "MUHAMMED"
    }


    tools {
        maven 'mymaven'
    }

    options {
        skipStagesAfterUnstable()
    }

    stages {

        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
                echo "hello $NAME"
            
            }
        }

        stage('Test A') {
            steps {
                sh 'mvn test'
        stage (test b){
            echo "stage stage 123b"
        }
        stage (test c){
            echo  "qwert"
        }

         }
        }

            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        

        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}